server:
  port: 8095
#  contextPath: /calculator

  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t %r %s %b %D"
    basedir: ../tomcat
    rotate: true

liquibase:
  change-log:
    classpath:liquibase-changelog.xml

calculator:
  threads:
    pool-size: 10

---
spring:
  profiles: local, default

  h2:
    console:
      enabled: false # Enable the console.
      path: /h2-console/* # Path at which the console will be available.
      settings:
        trace: false # Enable trace output.
        web-allow-others: false # Enable remote access.

  datasource:
    url: jdbc:h2:~/h2/calculator
    username: SA
    password:
    driverClassName: org.h2.Driver
#    defaultSchema:
#    maxPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#      dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.springframework: INFO
    org.apache: INFO
    org.springframework.data: DEBUG
    org.springframework.data.mongodb.core.MongoDbUtils: INFO
    org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module: INFO
    pl.sjacek: DEBUG

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/calculator
    username: myuser
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLDialect

